import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ScrollProgress from '../components/scrollProgress/scrollProgress'
import Header from '../components/header/header'
import AboutMe from '../components/aboutMe/aboutMe'
import Skills from '../components/skills/skills'
import Experiecne from '../components/experience/experiecne'
import styles from '../styles/Home.module.css'

// 🧑🏻‍💻
const Home: NextPage = () => {
  return (

    <div className={styles.home_wrapper}>

      <Head>
        <title>Surya - Front End Developer 💻</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Experiecne />

      {/* <ScrollProgress />
      <Header />
      <AboutMe />

      <Skills title={'Front End Skills'} />
      <div style={{height:'300px',width:'150px'}} />
      <div style={{height:'300px',width:'150px'}} />
      <div style={{height:'300px',width:'150px'}} /> */}

    </div>
  )
}

export default Home
