import type { NextPage } from 'next'
import {useRef} from 'react'
import Head from 'next/head'

import { CurrentSectionProvider } from '../contexts/currentSectionContext'

import ScrollProgress from '../components/scrollProgress/scrollProgress'
import Experiecne from '../components/experience/experiecne'
import styles from '../styles/Home.module.css'
// import Image from 'next/image'
import Header from '../components/header/header'
import AboutMe from '../components/aboutMe/aboutMe'
import Skills from '../components/skills/skills'
import SkillTile from '../components/skills/skillTile/skillTile'
import SkillInfoPopUp from '../components/skills/skillInfoPopUp/skillInfoPopUp'
import SideMenu from '../components/sideMenu/sideMenu'
import ContactMe from '../components/contactMe/contactMe'
import Footer from '../components/footer/footer'


import {
  reactJsInfo, nextJsInfo, htmlInfo, cssInfo, flutterInfo, threeJs, postgresInfo, mongoDBInfo, nodeJsInfo, expressJSInfo, FirebaseInfo, supaBaseInfo, javaScriptInfo, typeScriptInfo, javaInfo, dartInfo, vsCodeInfo, figmaInfo, gitInfo
} from '../consts/skillsData'



//design Two
// 🧑🏻‍💻
// Surya - Front End Developer 💻
const Home: NextPage = () => {

  const sectionValueRef = useRef({toggleSection:(section:string)=>{}})

  return (
    <>
    
    <BackGround />
    
    <div className={styles.home_wrapper}>

      <Head>
        <title>SURYA | Front-End Developer 💻</title>
        <meta name="description" content="SURYA | Front-End Developer"/>
        <link rel="icon" href="/profileThumb.jpeg" />

        <meta property="og:title" content="SURYA | Front-End Developer" />
        <meta property="og:url" content="https://surya-master-developer.vercel.app/" />
        <meta property="og:description" content="Surya Portfolio" />
        <meta property="og:image" content="https://surya-master-developer.vercel.app/profileThumb.jpeg"/>
        <meta property="og:type" content="website" />
      </Head>


    <CurrentSectionProvider value={sectionValueRef.current} >

      <ScrollProgress />
      


        <div className={styles.home_body_wrapper}>

        <div className={styles.home_content_wrapper}>
          
          <div className={styles.home_content}>

            <section id='section_1'>
              <Header />
              <AboutMe />
            </section>

            <section id='section_2'>
              <Skills title={'Front End Skills'} section={'section_2'}>
                  <SkillTile title={'React Js'} info={reactJsInfo} />
                  <SkillTile title={'Next Js'} info={nextJsInfo} tag={'BUILT WITH'} runningText={'Yes this project is built with NEXT JS'}/>
                  <SkillTile title={'HTML'} info={htmlInfo} />
                  <SkillTile title={'CSS'} info={cssInfo} />
                  <SkillTile title={'Flutter'} info={flutterInfo} />
                  <SkillTile title={'Three Js'} info={threeJs} tag={'BETA'} />
              </Skills>
            </section>


            <section id='section_3'>
              <Skills title={'Backend End Skills'} section={'section_3'}>
                  <SkillTile title={'Postgres SQL'} info={postgresInfo} />
                  <SkillTile title={'Mongo DB'} info={mongoDBInfo} />
                  <SkillTile title={'Node JS'} info={nodeJsInfo} />
                  <SkillTile title={'Express'} info={expressJSInfo} />
                  <SkillTile title={'Firebase'} info={FirebaseInfo} />
                  <SkillTile title={'Supabase'} info={supaBaseInfo} />
              </Skills>
            </section>


            <section id='section_4'>
              <Skills title={'Programing Languages'} section={'section_4'}>
                  <SkillTile title={'Java Script'} info={javaScriptInfo} />
                  <SkillTile title={'Type Script'} info={typeScriptInfo} tag={'BUILT WITH'} runningText={'Yes this project is built with Type Script'}/>
                  <SkillTile title={'Dart'} info={dartInfo} />
                  <SkillTile title={'Java'} info={javaInfo} />
              </Skills>
            </section>


            <section id='section_5'>
              <Skills title={'Tools I Use'} section={'section_5'}>
                  <SkillTile title={'VS Code'} info={vsCodeInfo} />
                  <SkillTile title={'Git'} info={gitInfo} />
                  <SkillTile title={'Figma'} info={figmaInfo} />
              </Skills> 
            </section>


            <section id='section_6'>
              <Experiecne />
            </section>

            <section id='section_7'>
              <ContactMe />
            </section>


              <Footer />

          </div>
        </div>


        <SideMenu />


        </div>


        <SkillInfoPopUp />

        </CurrentSectionProvider >
      

    </div>
    </>


  )


}

export default Home


function BackGround(){
  return(
    <div className={styles.fixed_BG_image}>
      <p>
        FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS REACT-NATIVE  WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS REACT-NATIVE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS REACT-NATIVE  ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS REACT-NATIVE  CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS REACT-NATIVE  WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS REACT-NATIVE  WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS CHROME WEB-DEV MOBILE-DEV FLUTTER REACT-JS REACT-NATIVE NEXT-JS ANDROID IOS WINDOWS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END SPACE INTERSTELLAR NEBULA SIRIUS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS FRONT-END FLUTTER REACT-JS REACT-NATIVE NEXT-JS THREE-JS NODE-JS EXPRESS POSTGRES-SQL SUPABASE FIREBASE MONGODB UI/UX FIGMA ADOBE-XD ANDROID IOS WINDOWS LINUX CHROME WEB-DEV MOBILE-DEV SOFTWARE FRONT-END


        
      </p>
    </div>
  )
}


// FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWAREFLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWAREFLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWAREFLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE 
//         FLUTTER REACT-JS REACT-NATIVE WEB-DEV SOFTWARE
